import "./globals.css";
// import type { Metadata } from "next";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

import UserContextProvider from "@/context/userProvider";

// other imports

import { Header, Footer } from "@/components";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <ToastContainer />
          {/* header component */}
          <Header />
          {children}
          {/* footer component */}
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  );
}
